/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ufpr.sistemapedidos.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author samue
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Trabalho Java");

        //Listeners que fecham qualquer JInternalFrame que tenha sido aberto antes
        jMenuItemCadastroClientes.addActionListener(
                new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (jDesktopPanePrincipal.getAllFrames().length == 0) {
                    jDesktopPanePrincipal.add(new TelaClientes());

                } else {
                    jDesktopPanePrincipal.remove(0);
                    jDesktopPanePrincipal.add(new TelaClientes());
                    revalidate();
                    repaint();
                }
            }
        });
        jMenuItemCadastroProdutos.addActionListener(
                new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (jDesktopPanePrincipal.getAllFrames().length == 0) {
                    jDesktopPanePrincipal.add(new TelaProdutos());

                } else {
                    jDesktopPanePrincipal.remove(0);
                    jDesktopPanePrincipal.add(new TelaProdutos());
                    revalidate();
                    repaint();
                }
            }
        });
        jMenuItemCadastroPedido.addActionListener(
                new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (jDesktopPanePrincipal.getAllFrames().length == 0) {
                    jDesktopPanePrincipal.add(new TelaPedidos());

                } else {
                    jDesktopPanePrincipal.remove(0);
                    jDesktopPanePrincipal.add(new TelaPedidos());
                    revalidate();
                    repaint();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCadastroClientes = new javax.swing.JMenuItem();
        jMenuItemCadastroProdutos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCadastroPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(476, 635));

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemCadastroClientes.setText("Cadastro de Clientes");
        jMenuItemCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadastroClientes);

        jMenuItemCadastroProdutos.setText("Cadastro de Produtos");
        jMenuItemCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadastroProdutos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pedidos");

        jMenuItemCadastroPedido.setText("Cadastrar Pedido");
        jMenuItemCadastroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroPedidoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCadastroPedido);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        setBounds(0, 0, 510, 682);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroClientesActionPerformed
        TelaClientes telaClientes = new TelaClientes();
        jDesktopPanePrincipal.add(telaClientes);
        telaClientes.setVisible(true);
        try {
            telaClientes.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemCadastroClientesActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

        TelaClientes telaClientes = new TelaClientes();
        jDesktopPanePrincipal.add(telaClientes);
        telaClientes.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutosActionPerformed
        TelaProdutos telaProdutos = new TelaProdutos();
        jDesktopPanePrincipal.add(telaProdutos);
        telaProdutos.setVisible(true);
        try {
            telaProdutos.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadastroProdutosActionPerformed

    private void jMenuItemCadastroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroPedidoActionPerformed
        TelaPedidos telaPedidos = new TelaPedidos();
        jDesktopPanePrincipal.add(telaPedidos);
        telaPedidos.setVisible(true);
        try {
            telaPedidos.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadastroPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastroClientes;
    private javax.swing.JMenuItem jMenuItemCadastroPedido;
    private javax.swing.JMenuItem jMenuItemCadastroProdutos;
    // End of variables declaration//GEN-END:variables
}
